name = "formula-de-impacto"
pages_build_output_dir = "out"
compatibility_date = "2026-09-01"

[ai]
binding = "AI"

[[ratelimits]]
name = "LIMITE"
namespace_id = "1001"

[ratelimits.simple]
limit = 20
period = 60
